### ISSUE TITLE
max esc_attr issue in listing description textarea field

### ISSUE THREAD

**Issue by vairafiq** [sovware/directorist#1150]
esc_attr added extra dual "

**Comment by adminazhar** [comment]
@vairafiq @kowsar89 Instead of removing it, why not replace max with **maxlength** attribute?

It will be useful if the textarea field have maxlength attribute so users can specify maximum legth of the field.

`<textarea name="<?php echo esc_attr( $data['field_key'] ); ?>" id="<?php echo esc_attr( $data['field_key'] ); ?>" class="directorist-form-element" rows="<?php echo (int) $data['rows']; ?>" placeholder="<?php echo esc_attr( $data['placeholder'] ); ?>" maxlength="<?php echo esc_attr( $data_maxlength ); ?>" <?php $listing_form->required( $data ); ?>><?php echo esc_textarea( $data['value'] ); ?></textarea>`

**Comment by kowsar89** [comment]
@adminazhar maxlength added

**Comment by adminazhar** [comment]
@kowsar89 Perfect🙏
